#' Create a dataframe with Sleep-wake distribution, Time and Day
#'
#' Details in description
#'
#' @param file character vector
#' @param concat character [mean or median]
#' @param nepochs integer
#' @param epochlengthsec integer
#' @param concattimesec integer
#'
#' @return dataframe
#'
#' @examples
#' data(SleepWakeData)
#' SWdf<-Read_SW(SleepWakeData)
#'
#'@export
Read_SW<-function(Mres,concat="mean",nepochs=86400,epochlengthsec=4,concattimesec=300){
  
  df<-Read_Mouse_States(Mres,concat=concat,nepochs=nepochs,epochlengthsec=epochlengthsec,concattimesec=concattimesec)
  df<-AddDaySWdistr(df,concattimesec=concattimesec)
  df<-AddTimeHSWdistr(df,concattimesec=concattimesec)
  return(df)
  
}

#' Merging some days defined in sleep-wake table
#'
#' Details in description
#'
#' @param SWdf dataframe generated by Read_SW
#' @param Daysformat vector for merging days
#' @param concattimesec integer, time frame in seconds
#' @param TimeFormatsec integer, time scale to 1 in seconds (3600 for 1 hour)
#'
#' @return dataframe
#'
#' @examples
#' SWdf<-SWDayMerging(SWdf,Daysformat=list(c(1,2),3,4,c(1,2)))
#'
#'@export
SWdf_DayMerging<-function(SWdf,Daysformat,concattimesec=300,TimeFormatsec=3600){
  
  Res<-matrix(ncol=ncol(SWdf),nrow=0)
  
  colnames(Res)<-colnames(SWdf)
  
  for (i in seq(1,length(Daysformat))){
    Mfus<-DayFusion(SWdf,Daysformat[[i]])
    Res<-rbind(Res,Mfus)
  }
  
  
  Res<-AddTimeHSWdistr(Res,concattimesec=concattimesec)
  Res<-AddDaySWdistr(Res,concattimesec=concattimesec)
  
  return(Res)
}

#' Add a light-dark cycle, starting at 12
#'
#' Details in description
#'
#' @param SWdf dataframe generated by Read_SW
#'
#' @return dataframe
#'
#' @examples
#' SWdf<-AddLD(SWdf)
#'
#'@export
SWdf_AddLD<-function(SWdf){
  
  Modulo<-SWdf$Time %% 24
  Lightv<-rep(0,nrow(SWdf))
  Darkv<-rep(0,nrow(SWdf))
  Lightv[Modulo<=12 & Modulo != 0]<- 1
  Darkv[Modulo>12 | Modulo == 0]<- 1
  SWdf$Light<-Lightv
  SWdf$Dark<-Darkv
  return(SWdf)
  
}


#' Add a sleep deprivation column
#'
#' Details in description
#'
#' @param SWdf dataframe generated by Read_SW
#' @param Interval vector of 2 value for SD interval
#'
#' @return dataframe
#'
#' @examples
#' SWdf<-AddSD(SWdf,c(24,30))
#'
#'@export
SWdf_AddSD<-function(SWdf,Interval){
  idx<-SWdf$Time > Interval[1] & SWdf$Time <=Interval[2]
  if (! "SD" %in% colnames(SWdf)){
    SD<-rep(0,nrow(SWdf))
  }else{
    SD<-SWdf$SD
  }
  SD[idx]<-1
  SWdf$SD<-SD
  return(SWdf)
  
}

# Read sleep data
Read_Mouse_States<-function(Mres,concat="mean",nepochs=86400,epochlengthsec=4,concattimesec=300){
  
  # Mres<-matrix(ncol=length(files),nrow=nepochs)
  # colnames(Mres)<-files
  # 
  # for (f in files){
  #   x<-read.table(f,stringsAsFactors = F)
  #   Mres[,f]<-x$V1
  # }
  
  l_window<-concattimesec/epochlengthsec
  n_window<-nepochs/l_window
  McountW<-matrix(ncol=ncol(Mres),nrow=n_window)
  McountN<-matrix(ncol=ncol(Mres),nrow=n_window)
  McountR<-matrix(ncol=ncol(Mres),nrow=n_window)
  #LcountW<-matrix(ncol=ncol(Mres),nrow=n_window)
  #LcountS<-matrix(ncol=ncol(Mres),nrow=n_window)
  
  for (i in 1:n_window){
    for (j in 1:ncol(Mres)){
      tmp<-Mres[seq((i-1)*l_window + 1,i*l_window),j]
      McountW[i,j]<-length(tmp[tmp == "w" | tmp == "1"])
      McountN[i,j]<-length(tmp[tmp == "n" | tmp == "2"])
      McountR[i,j]<-length(tmp[tmp == "r" | tmp == "3"])
      
      # Add a SW seq
      tmpS<-tmp
      tmpS[tmp == "w" | tmp == "1"]<-1
      tmpS[tmp == "n" | tmp == "2" | tmp == "r" | tmp == "3"]<-0
      tmpS<-as.numeric(tmpS)
      
      # Mean continuous length of wake
      r<-rle(tmpS)
      m1<-mean(r$lengths[r$values == 1])
      m0<-mean(r$lengths[r$values == 0])
      #if (is.nan(m1) | m1 == 0){LcountW[i,j]<-0}else{LcountW[i,j]<-m1}
      #if (is.nan(m0) | m0 == 0){LcountS[i,j]<-0}else{LcountS[i,j]<-m0}
    }
  }
  
  if (nrow(Mres)>1){
    CatValW<-apply(McountW,1,concat)*epochlengthsec/3600
    CatValN<-apply(McountN,1,concat)*epochlengthsec/3600
    CatValR<-apply(McountR,1,concat)*epochlengthsec/3600
    CatValS<-CatValN+CatValR
    #LValW<-apply(LcountW,1,concat)*epochlengthsec/3600
    #LValS<-apply(LcountS,1,concat)*epochlengthsec/
    LValW<-round(apply(McountW,1,concat))
    LValS<-round(apply(McountN,1,concat)+apply(McountR,1,concat))
    
  }else{
    CatValW<-as.numeric(McountW[,1])*epochlengthsec/3600
    CatValN<-as.numeric(McountN[,1])*epochlengthsec/3600
    CatValR<-as.numeric(McountR[,1])*epochlengthsec/3600
    CatValS<-CatValN+CatValR
    #LValW<-as.numeric(LcountW[,1])*epochlengthsec/3600
    #LValS<-as.numeric(LcountS[,1])*epochlengthsec/3600
    LValW<-round(as.numeric(McountW[,1]))
    LValS<-round(as.numeric(McountN[,1])+as.numeric(McountR[,1]))
  }
  
  df <- data.frame(list(NREM=CatValN,REM=CatValR,Wake=CatValW,Sleep=CatValS,LenW=LValW,LenS=LValS))
  
  return(df)
  
}

# Simply add a column 'Day' that expect data to start from Day 1
AddDaySWdistr<-function(df,concattimesec=300){
  
  nepochPday <- 24*60*60/concattimesec # number of epochs per day
  Days <- as.integer(seq(0,nrow(df)-1)/nepochPday)+1
  
  df$Day<-Days
  
  return(df)
  
}

# Simply add a column 'Time' that expect data to start from Time H = 0
# Time is in hour
AddTimeHSWdistr<-function(df,concattimesec=300){
  
  TimeFormatsec=3600
  
  Time<- seq(1,nrow(df))*concattimesec/TimeFormatsec
  
  df$Time<-Time
  
  return(df)
  
}

# Fusion of some days (e.g. baseline days) using mean value
DayFusion<-function(SWdist,Days){
  
  dimM<-dim(SWdist[SWdist$Day == Days[1],])
  Mfus<- matrix(0,nrow=dimM[1],ncol=dimM[2])
  
  for (j in Days){
    Mfus<-Mfus+SWdist[SWdist$Day == j,]
  }
  Mfus<-Mfus/length(Days)
  
  return(Mfus)
  
}





